apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swapbox.postgrestSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swapbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
type: Opaque
stringData:
  password: {{ .Values.postgrest.dbPassword | quote }}
