apiVersion: v1
kind: Service
metadata:
  name: {{ include "swapbox.fullname" . }}-postgrest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swapbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "swapbox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
