{{- if .Values.martin.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "swapbox.fullname" . }}-martin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swapbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: martin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "swapbox.fullname" . }}-martin
  minReplicas: {{ .Values.martin.hpa.minReplicas }}
  maxReplicas: {{ .Values.martin.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.martin.hpa.targetCPUUtilizationPercentage }}
{{- end }}
