apiVersion: v1
kind: Service
metadata:
  name: tm-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: tasking-manager-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
