apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-frontend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontendReplicaCount }}
  selector:
    matchLabels:
      app: tasking-manager-frontend
  template:
    metadata:
      labels:
        app: tasking-manager-frontend
    spec:
      containers:
        - name: tm-frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          env:
            - name: REACT_APP_ORG_NAME
              value: {{ .Values.org.name }}
            - name: REACT_APP_ORG_CODE
              value: {{ .Values.org.code }}
            - name: REACT_APP_ORG_LOGO
              value: {{ .Values.org.logoUrl }}
            - name: REACT_APP_ORG_URL
              value: {{ .Values.org.url }}
            - name: REACT_APP_ORG_GITHUB
              value: {{ .Values.org.github }}
            - name: REACT_APP_APP_API_URL
              value: {{ .Values.apiUrl }}
            - name: REACT_APP_APP_API_VERSION
              value: v2
            - name: REACT_APP_OSM_SERVER_URL
              value: {{ .Values.osm.serverUrl }}
            - name: REACT_APP_OSM_SERVER_API_URL
              value: {{ .Values.osm.serverApiUrl }}
            - name: OSM_NOMINATIM_SERVER_URL
              value: {{ .Values.osm.nominatimServerUrl }}
            - name: REACT_APP_OSM_REGISTER_URL
              value: {{ .Values.osm.registerUrl }}
            - name: REACT_APP_ID_EDITOR_URL
              value: {{ .Values.osm.idEditorUrl }}
            - name: REACT_APP_POTLATCH2_EDITOR_URL
              value: {{ .Values.osm.potlatch2EditorUrl }}
            - name: REACT_APP_RAPID_EDITOR_URL
              value: {{ .Values.osm.rapidEditorUrl }}
            - name: OHSOME_STATS_TOKEN
              value: {{ .Values.ohsome.apiToken }}
            - name: OHSOME_STATS_TOPICS
              value: {{ .Values.ohsome.topics }}
            - name: TM_SECRET
              value: {{ .Values.secret }}
            - name: REACT_APP_CLIENT_ID
              value: {{ .Values.oAuth2.clientId }}
            - name: REACT_APP_REDIRECT_URI
              value: {{ .Values.oAuth2.redirectUri }}
            - name: REACT_APP_DEFAULT_CHANGESET_COMMENT
              value: {{ .Values.settings.defaultChangesetComment }}
            - name: REACT_APP_DEFAULT_LOCALE
              value: {{ .Values.settings.defaultLocale }}
            - name: REACT_APP_MAPPER_LEVEL_INTERMEDIATE
              value: {{ .Values.settings.mapperLevelIntermediate | quote }}
            - name: REACT_APP_MAPPER_LEVEL_ADVANCED
              value: {{ .Values.settings.mapperLevelAdvanced | quote }}
            - name: REACT_APP_IMPORT_MAX_FILESIZE
              value: {{ .Values.settings.importMaxFilesize | quote }}
            - name: REACT_APP_MAX_AOI_AREA
              value: {{ .Values.settings.maxAoiArea | quote }}
