apiVersion: v1
kind: Service
metadata:
  name: tm-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: tasking-manager-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
