apiVersion: v1
kind: Service
metadata:
  name: yesterdays-clip
  namespace: {{ .Release.Namespace }}
  labels:
    app: yesterdays-clip
spec:
  type: ClusterIP
  selector:
    app: yesterdays-clip
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
