apiVersion: batch/v1
kind: Job
metadata:
  name: georef-db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 21600 # six hours
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          command:
            ["uv", "run", "manage.py", "migrate"]
          env:
            - name: DJANGO_SECRET_KEY
              value: {{ .Values.django.secretKey }}
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ .Values.django.allowedHosts }}
            - name: DJANGO_DEBUG
              value: "{{ .Values.django.debug }}"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: host
            - name: PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: dbname
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: port
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: georef-db-app
                  key: password
